'use client';
import { useState,useRef } from 'react';
import { BookOpen, Flame, Heart, Feather, ArrowUp, Compass, Backpack, Settings2, Swords, RotateCcw, LoaderCircle, KeyRound, ChevronRight } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Progress } from '@/components/ui/progress';
import { type Character,type Entry,type State,initialState,opening,attributes,bonus,characterSchema,demoTurn } from '@/lib/game';
export default function Home(){
 const [character,setCharacter]=useState<Character>({name:'',origin:'',goal:'',weapon:''});
 const [state,setState]=useState(initialState);const [entries,setEntries]=useState<Entry[]>([]);const [started,setStarted]=useState(false);const [mode,setMode]=useState<'demo'|'ai'>('demo');
 const [action,setAction]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [settings,setSettings]=useState(false);const [rules,setRules]=useState(false);const [reset,setReset]=useState(false);const [key,setKey]=useState('');const [draftKey,setDraftKey]=useState('');const lock=useRef(false);const storyRef=useRef<HTMLDivElement>(null);
 const current=entries.at(-1)??opening;
 function start(nextMode:'demo'|'ai'){
  const parsed=characterSchema.safeParse(character);if(!parsed.success){setError('Preencha seu nome, sua origem, sua motivação e seu objeto pessoal.');return;}
  setCharacter(parsed.data);setError('');if(nextMode==='ai'&&!key){setSettings(true);return;}
  setMode(nextMode);setState(initialState);setEntries([opening]);setStarted(true);
 }
 function configure(){if(draftKey.trim().length<20){setError('Cole uma chave válida do Google AI Studio.');return;}setKey(draftKey.trim());setDraftKey('');setSettings(false);setError('');if(!started){const parsed=characterSchema.safeParse(character);if(parsed.success){setCharacter(parsed.data);setMode('ai');setState(initialState);setEntries([opening]);setStarted(true);}}else setMode('ai');}
 async function act(text:string){
  if(lock.current||!text.trim())return;const chosen=text.trim().slice(0,600);lock.current=true;setBusy(true);setError('');
  try{
   if(mode==='demo'){const result=demoTurn(state,character,chosen);setState(result.state);setEntries(e=>[...e,result.entry]);}
   else {const response=await fetch('/api/turn',{method:'POST',headers:{'Content-Type':'application/json','x-narrator-key':key},body:JSON.stringify({character,state,action:chosen,history:entries.slice(-8).map(({action,text})=>({action,text}))}),signal:AbortSignal.timeout(70000)});const result=await response.json() as {error?:string;state:State;entry:Entry};if(!response.ok)throw new Error(result.error??'Não foi possível ouvir o narrador.');setState(result.state);setEntries(e=>[...e,result.entry]);}
   setAction('');requestAnimationFrame(()=>storyRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));
  }catch(e){setAction(chosen);setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'O narrador demorou a responder. Tente novamente.');}finally{setBusy(false);lock.current=false;}
 }
 const demoEnded=mode==='demo'&&state.turn>=3;
 return <div className="app-shell">
  <header className="masthead"><a className="brand" href="/" aria-label="Crônicas do Véu, início"><BookOpen size={23}/><span>CRÔNICAS <i>do</i> VÉU</span></a><div className="header-actions"><span className="edition">RPG SOLO · EXPERIMENTO 01</span><button className="icon-button" onClick={()=>setRules(true)} aria-label="Como jogar"><BookOpen size={19}/></button><button className="icon-button" onClick={()=>{setError('');setSettings(true);}} disabled={busy} aria-label="Configurar narrador de IA"><Settings2 size={19}/></button></div></header>
  {!started?<main className="creation">
   <section className="creation-intro"><p className="eyebrow">UMA HISTÓRIA AINDA NÃO ESCRITA</p><h1>Todo caminho<br/>deixa <em>marcas.</em></h1><p className="intro-copy">Uma vila sob a chuva. Uma entrega aparentemente simples. Alguém que não vai esquecer de você.</p><div className="chapter-teaser"><span className="chapter-number">I</span><div><p className="eyebrow">O PRIMEIRO CAPÍTULO</p><h2>O sino sem voz</h2><p>Vila de Breu, ao cair da noite.</p></div></div><p className="intro-note">Você descreve o que tenta fazer.<br/>O mundo responde às suas escolhas.</p></section>
   <section className="creation-form"><div className="section-heading"><Feather size={21}/><h2>Quem chega a Breu?</h2></div><p className="muted">Comece pequeno. O resto, você descobre no caminho.</p><form onSubmit={e=>{e.preventDefault();start('ai');}}>
    <label>Seu nome<input autoComplete="off" maxLength={40} required placeholder="Como chamam você?" value={character.name} onChange={e=>setCharacter({...character,name:e.target.value})}/></label>
    <div className="form-row"><label>De onde você vem<input maxLength={60} required value={character.origin} onChange={e=>setCharacter({...character,origin:e.target.value})} placeholder="Profissão ou origem"/></label><label>Seu objeto pessoal<input maxLength={60} required placeholder="Escolha um objeto comum" value={character.weapon} onChange={e=>setCharacter({...character,weapon:e.target.value})}/></label></div>
    <p className="field-note">Espada, machado ou frigideira: todo objeto começa com poder comum.</p>
    <label>O que move você?<textarea maxLength={160} required rows={2} placeholder="O que seu personagem procura?" value={character.goal} onChange={e=>setCharacter({...character,goal:e.target.value})}/></label>
    <div className="starting-stats">{attributes.map(a=><div key={a}><strong>{bonus(character,a)}</strong><span>{a}</span></div>)}</div>
    {error&&!settings&&<p role="alert" className="error">{error}</p>}
    <button className="primary-button" type="submit"><Feather size={18}/> Começar com narrador de IA <ChevronRight size={18}/></button>
    <button className="secondary-button demo-button" type="button" onClick={()=>start('demo')}>Experimentar demonstração sem IA</button>
    <p className="session-note">IA: requer sua chave do Gemini. Demonstração: 3 cenas com roteiro fixo. A aventura fica nesta sessão; recarregar a página reinicia o jogo.</p>
   </form></section>
  </main>:<main className="game-layout">
   <aside className="character-panel"><div className="identity"><span className="eyebrow">SEU PERSONAGEM</span><h2>{character.name}</h2><p>{character.origin}</p></div><div className="resource"><div><span><Heart size={15}/> Vida</span><b>{state.hp}<small> / 12</small></b></div><Progress value={state.hp/12*100} aria-label={`Vida: ${state.hp} de 12`} className="health-bar"/></div><div className="resource"><div><span><Flame size={15}/> Energia</span><b>{state.energy}<small> / 6</small></b></div><Progress value={state.energy/6*100} aria-label={`Energia: ${state.energy} de 6`} className="energy-bar"/></div><div className="attributes">{attributes.map(a=><div key={a}><span>{a}</span><strong>+{bonus(character,a)}</strong></div>)}</div>
    <section className="side-section"><h3><Backpack size={16}/> Na mochila</h3><p>{character.weapon}</p><span className="muted small">Objeto comum · poder inicial equilibrado</span><p>Capa de viagem</p></section><section className="side-section"><h3><Flame size={16}/> Magia conhecida</h3><p>Centelha <span className="muted">· 2 energia</span></p><span className="muted small">Uma pequena chama. Nada maior que isso, por enquanto.</span></section>
    <button className="reset-button" disabled={busy} onClick={()=>setReset(true)}><RotateCcw size={14}/> Novo personagem</button>
   </aside>
   <section className="adventure"><div className="story-topline"><span><Compass size={15}/>{state.location}</span><span className="turn">TURNO {String(state.turn).padStart(2,'0')}</span></div><div className="chapter-title"><p className="eyebrow">CAPÍTULO I</p><h1>O sino sem voz</h1><span className={`mode-badge ${mode==='ai'?'ai':''}`}>{mode==='ai'?'NARRADOR · GEMINI':'DEMONSTRAÇÃO · SEM IA'}</span></div>
    {entries.length>1&&<details className="past"><summary>Ler acontecimentos anteriores ({entries.length-1})</summary>{entries.slice(0,-1).map((e,i)=><article key={i}>{e.action&&<p className="past-action">Você: {e.action}</p>}<p>{e.text}</p>{e.test&&<small>{e.test}</small>}</article>)}</details>}
    <div className="current-scene" ref={storyRef} aria-live="polite" aria-busy={busy}>{current.action&&<div className="player-action"><Feather size={15}/><span>{current.action}</span></div>}<div className="prose">{current.text.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div>{current.test&&<div className="test-result"><Swords size={14}/><span>{current.test}</span></div>}</div>
    <section className="action-area"><h2>{demoEnded?'Sua próxima história pode ser livre.':'O que você faz?'}</h2>{demoEnded?<button className="primary-button" onClick={()=>setSettings(true)}><KeyRound size={16}/> Conectar o narrador de IA</button>:<><div className="choices">{current.choices.map((choice,i)=><button key={choice} disabled={busy} onClick={()=>act(choice)}><span>{String(i+1).padStart(2,'0')}</span>{choice}<ChevronRight size={15}/></button>)}</div>{mode==='ai'?<form className="action-form" onSubmit={e=>{e.preventDefault();act(action);}}><label htmlFor="action">Ou tente algo seu</label><div className="action-input"><textarea id="action" rows={2} maxLength={600} value={action} disabled={busy} onChange={e=>setAction(e.target.value)} placeholder="Descreva uma ação, uma pergunta ou uma ideia…"/><button type="submit" disabled={busy||!action.trim()} aria-label="Enviar ação">{busy?<LoaderCircle className="spin" size={20}/>:<ArrowUp size={21}/>}</button></div><p className="field-note">Uma ação por vez. Criatividade é bem-vinda; o resultado vem do mundo.</p></form>:<p className="demo-notice">Nesta demonstração, as opções avançam um roteiro fixo. Conecte a IA para escrever ações livres.</p>}</>}
    {busy&&<p role="status" className="loading"><LoaderCircle size={16} className="spin"/> O narrador está ouvindo sua ideia…</p>}{error&&!settings&&<p className="error" role="alert">{error}</p>}</section>
   </section>
   <aside className="journal-panel"><p className="eyebrow">SEU DIÁRIO</p><section><span className="journal-index">01 / MOTIVAÇÃO</span><h3>O que trouxe você</h3><p>{character.goal}</p></section><section><span className="journal-index">02 / PONTO DE PARTIDA</span><h3>Uma entrega ao moinho</h3><p>Mara ofereceu abrigo em troca de uma entrega. Você decide o que fazer com a proposta.</p></section><section><span className="journal-index">03 / UM ROSTO RECORRENTE</span><h3>O outro viajante</h3><p>{state.rival}</p></section><div className="journal-footer"><Feather size={22}/><p>Algumas escolhas deixam<br/>marcas em outras pessoas.</p></div></aside>
  </main>}
  <footer className="page-footer"><span>CRÔNICAS DO VÉU</span><span>Fantasia, escolhas e consequências.</span><button onClick={()=>setRules(true)}>Como jogar</button></footer>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>Seu narrador de IA</DialogTitle><DialogDescription>Conecte uma chave do Gemini para interpretar ações livres.</DialogDescription></DialogHeader><p>Usamos o Gemini 2.5 Flash-Lite. O Google oferece uma faixa gratuita sujeita a cotas e disponibilidade da sua conta.</p><a className="external-link" href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">Criar ou consultar chave no Google AI Studio ↗</a><label>Chave da API<input type="password" autoComplete="off" spellCheck={false} value={draftKey} onChange={e=>setDraftKey(e.target.value)} placeholder="Cole sua chave aqui"/></label><p className="field-note">A chave fica apenas na memória desta página e é enviada ao nosso servidor para acessar o Google. A história e suas ações são enviadas ao Gemini; o uso gratuito pode ser usado pelo Google para melhorar seus produtos. Não inclua dados pessoais.</p>{key&&<p className="muted">Há uma chave configurada nesta sessão. A conexão é verificada ao enviar uma ação.</p>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary-button" disabled={!draftKey.trim()} onClick={configure}>{started?'Usar IA nesta aventura':'Entrar na aventura com IA'}</button>{key&&<button className="secondary-button" onClick={()=>{setKey('');setDraftKey('');setSettings(false);setMode('demo');setState(initialState);setEntries([opening]);setError('');}}>Desconectar e reiniciar demonstração</button>}<p className="field-note">Duas chamadas por ação: interpretação e narração. Nenhuma contratação ou cobrança é ativada pelo jogo. Se sua conta já usa faturamento, aplicam-se as condições do Google. <a href="https://ai.google.dev/gemini-api/docs/pricing" target="_blank" rel="noreferrer">Consultar preços e limites.</a></p></DialogContent></Dialog>
  <Dialog open={rules} onOpenChange={setRules}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>O mundo responde. Você escolhe.</DialogTitle><DialogDescription>Regras pequenas para uma aventura aberta.</DialogDescription></DialogHeader><p>Escolha uma sugestão ou, com a IA conectada, descreva uma ação. O narrador interpreta sua intenção; o jogo resolve os testes.</p><ul className="rules-list"><li><b>Testes:</b> d12 + atributo. Dificuldade 6, 9 ou 12. Até 2 pontos abaixo: sucesso com custo. Abaixo disso: fracasso.</li><li><b>Consequências:</b> apenas ações com risco físico podem tirar vida. Com 1 de vida, uma derrota força sua retirada.</li><li><b>Equipamento:</b> seu objeto é comum, independentemente do nome. A frigideira também vale.</li><li><b>Magia:</b> Centelha cria uma pequena chama e gasta 2 de energia. Descansar em segurança recupera até 3 de vida e 2 de energia.</li><li><b>Memória:</b> o narrador recebe um resumo da aventura e as últimas cenas. Este MVP mantém o progresso somente enquanto a página está aberta.</li></ul></DialogContent></Dialog>
  <AlertDialog open={reset} onOpenChange={setReset}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Começar uma nova história?</AlertDialogTitle><AlertDialogDescription>A aventura atual será encerrada. O progresso desta sessão será perdido.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Continuar aventura</AlertDialogCancel><AlertDialogAction onClick={()=>{setStarted(false);setEntries([]);setState(initialState);setAction('');setError('');}}>Criar personagem</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
